### ISSUE TITLE
使用wox的时候发送失败，请问这个插件该如何配置啊

### ISSUE THREAD

**Issue by WissenY** [simonli/Wox.Plugin.Flomo#1]

**Comment by simonli** [comment]
一，打开Wox的配置页，如下图：
![image](https://user-images.githubusercontent.com/37920/106878372-d8d86800-6714-11eb-96b4-bb5c0f1743be.png)


二，打开该插件的安装目录，找到红框的文件
![image](https://user-images.githubusercontent.com/37920/106877873-3e782480-6714-11eb-8c2b-ef45858834e0.png)

三，打开文件如下图，配置红框的值为你自己的Flomo API，保存后重启Wox即可

![image](https://user-images.githubusercontent.com/37920/106878069-7da67580-6714-11eb-9e5b-79b1da932c91.png)

**Comment by Java2Boy** [comment]
api现在改收费的了，免费用户无法使用？
